name: RDP

on:
  workflow_dispatch:

jobs:
  setup-rdp:
    runs-on: windows-latest
    timeout-minutes: 3600

    steps:
      - name: Enable Remote Desktop
        run: |
          # Bật RDP
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' `
                           -Name "fDenyTSConnections" -Value 0 -Force
          # Cho phép qua firewall
          netsh advfirewall firewall add rule name="RDP" dir=in action=allow protocol=TCP localport=3389
          Restart-Service -Name TermService -Force

      - name: Create RDP User
        run: |
          $User = "admin"
          $Password = "Cuongtrinh1235@"
          net user $User $Password /add
          net localgroup administrators $User /add
          Write-Host "✅ User: $User | Password: $Password"

      - name: Download and Install Tailscale
        run: |
          Invoke-WebRequest -Uri "https://pkgs.tailscale.com/stable/tailscale-setup-latest-amd64.msi" -OutFile tailscale.msi
          Start-Process msiexec.exe -ArgumentList '/i tailscale.msi /quiet /norestart' -Wait

      - name: Authenticate to Tailscale
        env:
          TAILSCALE_AUTH_KEY: ${{ secrets.TAILSCALE_AUTH_KEY }}
        run: |
          tailscale up --authkey $Env:TAILSCALE_AUTH_KEY --hostname "GitHub-RDP" --accept-routes --accept-dns
          tailscale ip -4 > tailscale-ip.txt

      - name: Show Connection Info
        run: |
          $ip = Get-Content tailscale-ip.txt
          Write-Host "==============================="
          Write-Host "✅ Connect to RDP via Tailscale"
          Write-Host "IP: $ip"
          Write-Host "User: admin"
          Write-Host "Pass: Cuongtrinh1235@"
          Write-Host "==============================="
